# Generated by Django 5.1.3 on 2024-11-26 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
