# Generated by Django 5.1.3 on 2024-11-26 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_remove_listing_watch_list_listing_watch_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="listing_id",
            new_name="listing",
        ),
        migrations.RenameField(
            model_name="bid",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="article",
            new_name="listing",
        ),
    ]
