# Generated by Django 5.1.3 on 2024-11-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_remove_listing_watch_list_watchlist_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="listing",
            field=models.ManyToManyField(
                related_name="watchlist_listing", to="auctions.listing"
            ),
        ),
    ]
