# Generated by Django 5.1.3 on 2024-11-26 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_listing_commented_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="commented_by",
            new_name="added_by",
        ),
    ]
