# Generated by Django 5.1.3 on 2024-11-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_winninghistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="closed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="winninghistory",
            name="wins",
        ),
        migrations.AddField(
            model_name="winninghistory",
            name="wins",
            field=models.ManyToManyField(to="auctions.listing"),
        ),
    ]
